// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoSalaoAPI.Models;

namespace ProjetoSalaoAPI.Migrations
{
    [DbContext(typeof(ProjetoSalaoAPIContext))]
    partial class ProjetoSalaoAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjetoSalaoAPI.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuar")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("Senha");

                    b.HasKey("IdUsuar");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
